require_relative '../../../../../gen/Design.ORiN3.Common/V1/orin3_common_pb'
require_relative '../message_client_error'
require_relative '../../../orin3/provider/orin3_binary_converter'

module O3P
  include Message::ORiN3::Provider::V1::AutoGenerated
end

module O3
  include Design::ORiN3::Common::V1::AutoGenerated
  include Message::ORiN3::Provider::V1::AutoGenerated::ResourceOpener
end

module Grpc
  module Client
    module ORiN3
      module Provider
        class ORiN3Module < ORiN3BaseObject
          attr_reader :created_datetime
          include ORiN3ChildCreator

          def initialize(channel, internal_id, created_datetime)
            @created_datetime = created_datetime
            super(channel, internal_id)
          end
        end
      end
    end
  end
end